/* ============================================================================
   IP7 · Catálogo SIEMENS — Configuración y datos
   ----------------------------------------------------------------------------
   TODO lo editable del sitio vive en este archivo. No hace falta tocar app.js.
   ========================================================================== */

const CONFIG = {
  cliente: 'SIEMENS',

  /* Logo del cliente. Si dejas la ruta de un archivo dentro de img/ el sitio lo usa;
     con null se muestra el nombre compuesto tipográficamente. */
  logoCliente: null,
  vigencia: '30 de abril de 2026',

  /* Correo que siempre va en copia en las cotizaciones */
  copiaCotizacion: 'mercadeo@ip7.com.co',

  /* Cantidad mínima única para TODO el catálogo.
     - null  -> cada producto usa su propia cantidad mínima (la del catálogo).
     - 5     -> fuerza 5 unidades en todos los productos.                     */
  minimoGlobal: null,

  /* Mínimo por defecto cuando un producto no trae escala de precios */
  minimoPorDefecto: 10,

  /* --------------------------------------------------------------------
     EQUIPO COMERCIAL
     Rellena "whatsapp" (solo dígitos, con indicativo 57) y "email".
     Los que queden sin whatsapp no aparecen en la lista de WhatsApp;
     los que queden sin email no aparecen en el selector de cotización.
     -------------------------------------------------------------------- */
  comerciales: [
    { nombre: 'Sevastian',      cargo: 'Ejecutivo de cuenta SIEMENS',
      whatsapp: '',             email: 'ejecutivo.comercial3@ip7.com.co' },
    { nombre: 'Carlos Salinas', cargo: 'Dirección comercial',
      whatsapp: '573002176412', email: 'carlossalinas@ip7.com.co' }
  ],

  categorias: [
    { id: 'morrales',        nombre: 'Morrales y Maletines' },
    { id: 'bolsas',          nombre: 'Bolsas y Tulas' },
    { id: 'libretas',        nombre: 'Libretas y Oficina' },
    { id: 'boligrafos',      nombre: 'Bolígrafos' },
    { id: 'paraguas',        nombre: 'Paraguas y Gorras' },
    { id: 'bebidas',         nombre: 'Botilitos, Mugs y Café' },
    { id: 'tecnologia',      nombre: 'Tecnología' },
    { id: 'reconocimientos', nombre: 'Reconocimientos' },
    { id: 'textil',          nombre: 'Textil y Confección' },
    { id: 'publicidad',      nombre: 'Publicidad y POP' },
    { id: 'varios',          nombre: 'Varios' }
  ]
};

/* --------------------------------------------------------------------------
   PRODUCTOS
   escalas: [ [desde, hasta|null, precio], ... ]   precio en COP, sin IVA
   fotos:   nombres de archivo dentro de img/  (la primera es la principal)
   -------------------------------------------------------------------------- */
const PRODUCTOS = [
  /* ---------- Morrales y Maletines ---------- */
  { id:'morral-adula', cat:'morrales', nombre:'Morral Adula', ref:'NW8302', sinMarco:true,
    desc:'Compartimiento acolchado para laptop de 15" y espacio para tablet. Amplio interior para documentos, libros o cámara. Asas acolchadas y ajustables. Material: poliéster. Incluye placa metálica adicional para marca.',
    fotos:['morral-adula.jpg'], escalas:[[10,50,154300],[51,100,143300],[101,null,140000]] },
  { id:'maletin-neo', cat:'morrales', nombre:'Maletín Neo', ref:'VA-1041', sinMarco:true,
    desc:'Maletín para viaje en poliéster, con bolsillo exterior con cremallera y bolsillo guarda zapatos. Reata para cargar.',
    fotos:['maletin-neo.jpg'], escalas:[[10,50,153300],[51,100,142400],[101,null,139500]] },
  { id:'morral-portatil-14', cat:'morrales', nombre:'Morral Portátil 14 Lts.', ref:'BO0312', sinMarco:true,
    desc:'Morral con agarradera en aluminio y cargaderas ajustables. Compartimento con velcro para portátil de hasta 14" y otro con bolsillo interior para bolígrafo y libreta. Doble bolsillo frontal con cremallera. Incluye placa metálica para marcar láser.',
    fotos:['morral-portatil-14.jpg'], escalas:[[10,50,129000],[51,100,118500],[101,null,115900]] },
  { id:'canguro-master-ocean', cat:'morrales', nombre:'Canguro Master Ocean', ref:'VA-1077', sinMarco:true,
    desc:'Canguro en poliéster reciclado de residuos plásticos recuperados del océano. Tres compartimentos con cierre de cremallera. Incluye placa metálica para marcar.',
    fotos:['canguro-master-ocean.jpg'], escalas:[[10,50,108000],[51,100,97700],[101,null,95500]] },

  /* ---------- Bolsas y Tulas ---------- */
  { id:'bolsa-cambrel-baxter', cat:'bolsas', nombre:'Bolsa en Cambrel Baxter', ref:'VA-404', sinMarco:true,
    desc:'Bolsa en cambrel 80 gm sellada con agarraderas. Medidas: 38 cm x 40 cm. Manijas: 30 cm.',
    fotos:['bolsa-cambrel-baxter.jpg'], escalas:[[10,50,17300],[51,100,5100],[101,null,3500]] },
  { id:'bolsa-cambrel-petit', cat:'bolsas', nombre:'Bolsa en Cambrel Petit', ref:'VA-712', sinMarco:true,
    desc:'Sellada, con agarraderas. Medidas: 26.5 cm x 26.5 cm con fuelle de 8 cm en la base. Manijas: 14 cm.',
    fotos:['bolsa-cambrel-petit.jpg'], escalas:[[10,50,16800],[51,100,4500],[101,null,3000]] },
  { id:'slim-bag', cat:'bolsas', nombre:'Slim Bag', ref:'VA-404',
    desc:'Bolsa ecológica, útil para tiendas de comestibles, mercados o librerías. Medidas: 37 x 39,3 cm. Longitud manija: 44 cm.',
    fotos:['slim-bag.jpg'], escalas:[[10,50,17300],[51,100,5100],[101,null,3500]] },
  { id:'sporty-bag-aspen', cat:'bolsas', nombre:'Sporty Bag Aspen', ref:'VA-617', sinMarco:true,
    desc:'Bolsa tula en poliéster 210D. Medidas: 32 cm x 40.5 cm.',
    fotos:['sporty-bag-aspen.jpg'], escalas:[[10,50,19100],[51,100,6900],[101,null,5300]] },
  { id:'sporty-bag-ewok', cat:'bolsas', nombre:'Sporty Bag Ewok', ref:'VA-574', sinMarco:true,
    desc:'Bolsa en cambrel 80 gm cosida. Medidas: 41 cm x 31 cm. También disponible en azul, blanco y verde (colores no mostrados en la foto).',
    fotos:['sporty-bag-ewok.jpg'], escalas:[[10,50,17900],[51,100,5700],[101,null,4100]] },
  { id:'sporty-bag-eco-yute', cat:'bolsas', nombre:'Sporty Bag Eco Yute', ref:'VA-941', sinMarco:true,
    desc:'Bolsa en algodón de 280 gr, poliéster con base en yute y cordones en algodón para cerrar y cargar.',
    fotos:['sporty-bag-eco-yute.jpg'], escalas:[[10,50,26100],[51,100,13700],[101,null,12000]] },
  { id:'sporty-bag-evan', cat:'bolsas', nombre:'Sporty Bag Evan', ref:'VA-979', sinMarco:true,
    desc:'Bolsa tula en poliéster (imitación yute). Medidas: 33.5 cm x 41 cm.',
    fotos:['sporty-bag-evan.jpg'], escalas:[[10,50,24500],[51,100,12100],[101,null,10500]] },
  { id:'sporty-bag-zetta', cat:'bolsas', nombre:'Sporty Bag Zetta', ref:'VA-1180', sinMarco:true,
    desc:'Bolsa tula en algodón de 100 gr. Medidas: 37 cm x 41 cm. También disponible en amarillo (color no mostrado en la foto).',
    fotos:['sporty-bag-zetta.jpg'], escalas:[[10,50,23100],[51,100,10800],[101,null,9200]] },

  /* ---------- Libretas y Oficina ---------- */
  { id:'libreta-vincent', cat:'libretas', nombre:'Libreta Vincent', ref:'OF-599', sinMarco:true,
    desc:'Cubierta elaborada en corcho, 80 hojas de papel de 70 g reciclado con rayas.',
    fotos:['libreta-vincent.jpg'], escalas:[[10,50,34100],[51,100,17200],[101,null,15600]] },
  { id:'libreta-spyro', cat:'libretas', nombre:'Libreta Spyro', ref:'OF-497', sinMarco:true,
    desc:'Libreta de 80 hojas con rayas, cubierta en polipropileno. No incluye bolígrafo.',
    fotos:['libreta-spyro.jpg'], escalas:[[10,50,27100],[51,100,10300],[101,null,8800]] },
  { id:'libreta-brooch', cat:'libretas', nombre:'Libreta Brooch', ref:'OF0628', sinMarco:true,
    desc:'Funda de piel sintética con cierre magnético. Tamaño A5, 70 g, 80 hojas, con pegatinas de colores en el interior.',
    fotos:['libreta-brooch.jpg'], escalas:[[10,50,35100],[51,100,18200],[101,null,16700]] },
  { id:'libreta-legend', cat:'libretas', nombre:'Libreta Legend', ref:'OF-600', sinMarco:true,
    desc:'Cubierta en poliéster reciclado a partir de botellas plásticas, 80 hojas de papel crema de 70 g con rayas.',
    fotos:['libreta-legend.jpg'], escalas:[[10,50,32800],[51,100,15900],[101,null,14400]] },
  { id:'libreta-igor-jumbo', cat:'libretas', nombre:'Libreta Igor Jumbo', ref:'OF-434-3', sinMarco:true,
    desc:'Libreta con cubiertas en poliuretano con cierre elástico. 80 hojas color crema con rayas. También disponible en rojo, negro y gris (colores no mostrados en la foto).',
    fotos:['libreta-igor-jumbo.jpg'], escalas:[[10,50,32500],[51,100,15600],[101,null,14100]] },
  { id:'mini-libreta-like-it-eco', cat:'libretas', nombre:'Mini Libreta Like It Eco', ref:'OF-606', sinMarco:true,
    desc:'Mini libreta argollada de 50 hojas en papel blanco. Opcional con o sin bolígrafo (ref. CARTOON-MI). También disponible en rojo y azul marino (colores no mostrados en la foto).',
    fotos:['mini-libreta-like-it-eco.jpg'], escalas:[[10,50,23900],[51,100,8500],[101,null,5700]] },
  { id:'libreta-igor-80', cat:'libretas', nombre:'Libreta Igor 80 Hojas', ref:'OF-434', destacado:true, sinMarco:true,
    desc:'Libreta en poliuretano con cierre elástico. 80 hojas. No incluye bolígrafo.',
    fotos:['libreta-igor-80.jpg'], escalas:[[10,50,20500],[51,100,12500],[101,null,9700]] },
  { id:'memo-cube', cat:'libretas', nombre:'Memo Cube', ref:'OF0443',
    desc:'Set en forma de cubo con espacio para tarjetas o bolígrafos. Contiene taco de 5 colores de 100 hojas cada color.',
    fotos:['memo-cube.jpg'], escalas:[[10,50,30200],[51,100,19500],[101,null,16700]] },
  { id:'memo-sticky-set-ring', cat:'libretas', nombre:'Memo Sticky Set Ring', ref:'OF-532', sinMarco:true,
    desc:'Set de portastickies de cartón argollado doble O. 5 tacos de hojas autoadhesivas x 25 und. y 5 stickies de colores.',
    fotos:['memo-sticky-set-ring.jpg'], escalas:[[10,50,26400],[51,100,15700],[101,null,12900]] },
  { id:'sticky-set-eco', cat:'libretas', nombre:'Sticky Set Eco', ref:'OF-205', sinMarco:true,
    desc:'Libreta con 5 stickies de colores y taco de papel autoadhesivo. Medidas: 8 cm x 9 cm.',
    fotos:['sticky-set-eco.jpg'], escalas:[[10,50,17800],[51,100,7200],[101,null,4700]] },
  { id:'resaltador-zanzibar', cat:'libretas', nombre:'Resaltador Zanzibar', ref:'ES0292', sinMarco:true,
    desc:'Set de 5 resaltadores en estuche traslúcido plástico.',
    fotos:['resaltador-zanzibar.jpg'], escalas:[[10,50,22300],[51,100,11700],[101,null,8900]] },

  /* ---------- Bolígrafos ---------- */
  { id:'boligrafo-ventura-frost', cat:'boligrafos', nombre:'Ventura Frost', ref:'VENT-FROST', sinMarco:true,
    desc:'Bolígrafo plástico con clip metálico. Medidas: 14 cm.',
    fotos:['boligrafo-ventura-frost.jpg'], escalas:[[100,200,2800],[201,500,1900],[501,null,1400]] },
  { id:'boligrafo-ventura-eco', cat:'boligrafos', nombre:'Bolígrafo Ventura Eco', ref:'VENT-ECO-B', sinMarco:true,
    desc:'Bolígrafo plástico con parte inferior en bambú natural. Clip metálico. Mezcla con material ecológico en fibra de trigo. También disponible en rojo, verde y natural (colores no mostrados en la foto).',
    fotos:['boligrafo-ventura-eco.jpg'], escalas:[[100,200,3800],[201,500,2900],[501,null,2400]] },
  { id:'boligrafo-colby-gyro', cat:'boligrafos', nombre:'Bolígrafo Colby Gyro', ref:'COLGY GYRO', sinMarco:true,
    desc:'Bolígrafo metálico con stylus y mecanismo push. Incluye un spinner en bambú. Medidas: 14.5 cm. También disponible en negro y gris (colores no mostrados en la foto).',
    fotos:['boligrafo-colby-gyro.jpg'], escalas:[[50,100,9800],[101,300,8700],[301,null,8200]] },
  { id:'boligrafo-croma', cat:'boligrafos', nombre:'Bolígrafo "Croma"', ref:'BP300', sinMarco:true,
    desc:'Plástico. Cuerpo de diferentes colores. Bolígrafo retráctil con clip plástico del mismo color del cuerpo.',
    fotos:['boligrafo-croma.jpg'], escalas:[[100,200,2700],[201,500,1800],[501,null,1300]] },
  { id:'boligrafo-otto', cat:'boligrafos', nombre:'Bolígrafo Otto', ref:'BP240', sinMarco:true,
    desc:'Plástico. Cuerpo de color, botón pulsador y puntera color plata. Tinta negra.',
    fotos:['boligrafo-otto.jpg'], escalas:[[100,200,2700],[201,500,1800],[501,null,1300]] },
  { id:'boligrafo-touch-centauro', cat:'boligrafos', nombre:'Bolígrafo Touch Centauro', ref:'BP286', sinMarco:true,
    desc:'Metálico. Pulsador touch color plata, clip metálico, cuerpo negro mate y destapa electro plateado en la parte superior e inferior.',
    fotos:['boligrafo-touch-centauro.jpg'], escalas:[[50,100,4700],[101,300,3600],[301,null,3200]] },
  { id:'apuntador-laser', cat:'boligrafos', nombre:'Apuntador Láser', ref:'ES0707',
    desc:'Bolígrafo con linterna y láser, sistema de apertura twist. Incluye estuche metálico individual y 3 pilas de repuesto.',
    fotos:['apuntador-laser.jpg'], escalas:[[50,100,15200],[101,300,13900],[301,null,13400]] },

  /* ---------- Paraguas y Gorras ---------- */
  { id:'paraguas-easyroll-23', cat:'paraguas', nombre:'Paraguas Easyroll 23"', ref:'SO-89', sinMarco:true,
    desc:'Paraguas plegable en poliéster pongee 300T. Apertura y cierre automático.',
    fotos:['paraguas-easyroll-23.jpg'], escalas:[[20,50,114700],[51,100,107000],[101,null,104000]] },
  { id:'paraguas-gentle-27', cat:'paraguas', nombre:'Paraguas 27" Gentle', ref:'SO-70', sinMarco:true,
    desc:'Poliéster pongee 190T. Apertura automática, cierre manual. Marco en fibra de vidrio. También disponible en plateado (color no mostrado en la foto).',
    fotos:['paraguas-gentle-27.jpg'], escalas:[[20,50,107000],[51,100,99400],[101,null,96600]] },
  { id:'paraguas-freerain-23', cat:'paraguas', nombre:'Paraguas Freerain 23"', ref:'SO-50', sinMarco:true,
    desc:'Paraguas invertido (abre al revés) de 23". Poliéster pongee 190T doble tela. Apertura manual. También disponible en amarillo, verde, gris, azul marino y negro (colores no mostrados en la foto).',
    fotos:['paraguas-freerain-23.jpg'], escalas:[[20,50,58300],[51,100,51300],[101,null,49100]] },
  { id:'mini-paraguas-strap-21', cat:'paraguas', nombre:'Mini Paraguas Strap 21"', ref:'SO-43', sinMarco:true,
    desc:'Poliéster pongee 190T. Plegable, mango con acabado en caucho y herraje metálico. Apertura semiautomática. También disponible en rojo, naranja, amarillo, verde, azul y gris (colores no mostrados en la foto).',
    fotos:['mini-paraguas-strap-21.jpg'], escalas:[[20,50,49000],[51,100,42200],[101,null,40100]] },
  { id:'mini-paraguas-21', cat:'paraguas', nombre:'Mini Paraguas 21"', ref:'SO-72', sinMarco:true,
    desc:'Poliéster pongee 190T. Correa en velcro, mango en plástico y herraje metálico con fibra de vidrio blanco. Apertura y cierre automáticos con sistema antibrisa.',
    fotos:['mini-paraguas-21.jpg'], escalas:[[20,50,40000],[51,100,33300],[101,null,31300]] },
  { id:'paraguas-trendy-27', cat:'paraguas', nombre:'Paraguas Trendy Poliéster 27"', ref:'SO-17-2', destacado:true, sinMarco:true,
    desc:'Poliéster con interior plateado. Mango en espuma y herraje metálico. 8 cascos. Semiautomático. También disponible en rojo, verde, negro, naranja, morado, gris y amarillo (colores no mostrados en la foto).',
    fotos:['paraguas-trendy-27.jpg'], escalas:[[20,50,48300],[51,100,41300],[101,null,39400]] },
  { id:'gorra-acrilica', cat:'paraguas', nombre:'Gorra Acrílica', ref:'DP', sinMarco:true,
    desc:'Diseñada para brindar comodidad y estilo. El material acrílico ofrece durabilidad, suavidad y un ajuste perfecto.',
    fotos:['gorra-acrilica.jpg'], escalas:[[10,50,20300],[51,100,14900],[101,null,13500]] },
  { id:'gorra-brixton', cat:'paraguas', nombre:'Gorra Brixton', ref:'CAP-30', sinMarco:true,
    desc:'Gorra en poliéster de alta calidad, de 6 paneles, con visera indeformable, botón forrado y cierre de hebilla metálica.',
    fotos:['gorra-brixton.jpg'], escalas:[[10,50,27000],[51,100,21300],[101,null,19300]] },
  { id:'gorra-golf', cat:'paraguas', nombre:'Gorra Golf', ref:'CAP-13',
    desc:'5 paneles en dril liviano, visera indeformable, frente fusionado, encintado interior, tafilete sencillo y cierre plástico.',
    fotos:['gorra-golf.jpg'], escalas:[[10,50,19700],[51,100,14000],[101,null,12200]] },

  /* ---------- Botilitos, Mugs y Café ---------- */
  { id:'botilito-metalico-600', cat:'bebidas', nombre:'Botilito Metálico 600ml', ref:'MU-256', sinMarco:true,
    desc:'Metálico en aluminio, con tapa rosca. No apto para bebidas calientes.',
    fotos:['botilito-metalico-600.jpg'], escalas:[[10,50,26100],[51,100,18400],[101,null,16400]] },
  { id:'botilito-metalico-950', cat:'bebidas', nombre:'Botilito Metálico 950ml', ref:'MU-350', sinMarco:true,
    desc:'Botilito doble pared vacuum en acero inoxidable, con aislamiento térmico que mantiene la bebida fría entre 8-10 h o caliente 3-4 h aprox. También disponible en plateado (color no mostrado en la foto).',
    fotos:['botilito-metalico-950.jpg'], escalas:[[20,50,68100],[51,100,59900],[101,null,57300]] },
  { id:'cafetera-vidrio-600', cat:'bebidas', nombre:'Cafetera en Vidrio 600ml', ref:'MU-404', sinMarco:true,
    desc:'Cafetera prensa francesa con filtro de aluminio. Vidrio de borosilicato y tapa de bambú. Capacidad 600 ml. Empaque caja individual.',
    fotos:['cafetera-vidrio-600.jpg'], escalas:[[10,50,55300],[51,100,47200],[101,null,44700]] },
  { id:'botilito-sport-laguna', cat:'bebidas', nombre:'Botilito Sport Laguna', ref:'MU-11', sinMarco:true,
    desc:'Botilito en AS, con agarradera plástica y tapa rosca. Libre de BPA. También disponible en rojo y negro (colores no mostrados en la foto).',
    fotos:['botilito-sport-laguna.jpg'], escalas:[[10,50,29300],[51,100,20100],[101,null,17700]] },
  { id:'botilito-pet-610', cat:'bebidas', nombre:'Botilito en PET 610ml', ref:'MU-90', sinMarco:true,
    desc:'Botilito en PET con tapa en ABS super resistente, con empaque individual. Consultar inventario de tapas.',
    fotos:['botilito-pet-610.jpg'], escalas:[[10,50,19700],[51,100,10500],[101,null,8400]] },
  { id:'botilito-pvc-helice-650', cat:'bebidas', nombre:'Botilito en PVC Hélice 650ml', ref:'MU-59', destacado:true, sinMarco:true,
    desc:'Botilito en PVC atóxico, tapa rosca con pestaña y diseño ergonómico. Producción nacional. También disponible en verde, morado, naranja, negro, blanco, rosado, amarillo y rojo (colores no mostrados en la foto).',
    fotos:['botilito-pvc-helice-650.jpg'], escalas:[[10,50,19300],[51,100,10200],[101,null,8100]] },
  { id:'mug-capsul', cat:'bebidas', nombre:'Mug Capsul', ref:'T750', sinMarco:true,
    desc:'Mug doble pared. Interior de acero inoxidable 304 y exterior de polipropileno. Pintura acabado mate. También disponible en azul, rojo, rosado y blanco (colores no mostrados en la foto).',
    fotos:['mug-capsul.jpg'], escalas:[[10,50,26500],[51,100,17500],[101,null,15200]] },
  { id:'mug-plastico-350', cat:'bebidas', nombre:'Mug Plástico 350ml', ref:'MU-407', sinMarco:true,
    desc:'Mug plástico con interior en acero inoxidable. Taparrosca de seguridad. Empaque caja individual. También disponible en negro y blanco (colores no mostrados en la foto).',
    fotos:['mug-plastico-350.jpg'], escalas:[[10,50,32900],[51,100,23700],[101,null,21300]] },
  { id:'mug-ceramica-11oz', cat:'bebidas', nombre:'Mug Cerámica 11oz', ref:'MU-112', sinMarco:true,
    desc:'Cerámica con base en corcho y tapa plástica. No apto para microondas ni lavavajillas. Tapa protectora de cierre a presión. También disponible en azul oscuro con base de corcho (color no mostrado en la foto).',
    fotos:['mug-ceramica-11oz.jpg'], escalas:[[36,72,38300],[73,108,28900],[109,null,26800]] },
  { id:'mug-ceramica-tablero-11oz', cat:'bebidas', nombre:'Mug Cerámica Tablero 11oz', ref:'MU-06', sinMarco:true,
    desc:'Mug para escribir con tiza, borrable como un tablero. Incluye tiza blanca. Apto para microondas y lavavajillas. Empaque caja individual.',
    fotos:['mug-ceramica-tablero-11oz.jpg'], escalas:[[36,72,21500],[73,108,15100],[109,null,14000]] },
  { id:'mug-ceramica-10oz', cat:'bebidas', nombre:'Mug Cerámica 10oz', ref:'VA-126', sinMarco:true,
    desc:'Mug de cerámica en forma cuadrada. Apto para microondas y lavavajillas.',
    fotos:['mug-ceramica-10oz.jpg'], escalas:[[36,72,17500],[73,108,15900],[109,null,14900]] },

  /* ---------- Tecnología ---------- */
  { id:'speaker-bluetooth-eco-te423', cat:'tecnologia', nombre:'Speaker Bluetooth Eco', ref:'TE-423', sinMarco:true,
    desc:'Speaker Bluetooth 5.0 plástico con material ecológico de fibra de trigo. 1x3W con luz multicolor.',
    fotos:['speaker-bluetooth-eco-te423.jpg'], escalas:[[10,50,50500],[51,100,41200],[101,null,38600]] },
  { id:'speaker-bluetooth-rpet', cat:'tecnologia', nombre:'Speaker Bluetooth RPET', ref:'TE-541',
    desc:'Speaker Bluetooth de 3W en poliéster reciclado RPET y corcho. Empaque caja individual.',
    fotos:['speaker-bluetooth-rpet.jpg'], escalas:[[10,50,61400],[51,100,51800],[101,null,49100]] },
  { id:'speaker-bluetooth-te650', cat:'tecnologia', nombre:'Speaker Bluetooth Lantern', ref:'TE-650',
    desc:'Speaker Bluetooth plástico con manija en imitación cuero. Lector de tarjetas TF, puerto USB, puerto Tipo C y puerto AUX.',
    fotos:['speaker-bluetooth-te650.jpg'], escalas:[[10,50,135900],[51,100,125300],[101,null,121500]] },
  { id:'speaker-bluetooth-te276', cat:'tecnologia', nombre:'Speaker Bluetooth Light', ref:'TE-276', sinMarco:true,
    desc:'Speaker Bluetooth plástico de 3W con lector de tarjeta (no incluida), entrada AUX y 6 tipos de luz.',
    fotos:['speaker-bluetooth-te276.jpg'], escalas:[[10,50,70000],[51,100,60300],[101,null,57500]] },
  { id:'speaker-bluetooth-plant', cat:'tecnologia', nombre:'Speaker Bluetooth Plant', ref:'TE-549', sinMarco:true,
    desc:'Speaker plástico Bluetooth de 3W con luz LED multicolor y matera para plantas. Funciona como manos libres. Empaque caja individual.',
    fotos:['speaker-bluetooth-plant.jpg'], escalas:[[10,50,64300],[51,100,54700],[101,null,51900]] },
  { id:'speaker-bluetooth-eco-te600', cat:'tecnologia', nombre:'Speaker Bluetooth Eco Madera', ref:'TE-600', sinMarco:true,
    desc:'Speaker Bluetooth en madera con reloj digital, calendario y alarma. 3 niveles de intensidad de luz. Bluetooth 5.0.',
    fotos:['speaker-bluetooth-eco-te600.jpg'], escalas:[[10,50,120400],[51,100,111300],[101,null,108100]] },
  { id:'speaker-bluetooth-te361', cat:'tecnologia', nombre:'Speaker Bluetooth Shower', ref:'TE-36-1', sinMarco:true,
    desc:'Speaker Bluetooth en plástico con chupa, resistente al agua, 3W.',
    fotos:['speaker-bluetooth-te361.jpg'], escalas:[[10,50,39200],[51,100,29900],[101,null,27500]] },
  { id:'reloj-con-cargador', cat:'tecnologia', nombre:'Reloj con Cargador', ref:'TE-495', sinMarco:true,
    desc:'Cargador inalámbrico en bambú de 10W. Reloj digital con temperatura. Input DC 5V 1.5A, Output 1.1A 10W. Empaque caja individual.',
    fotos:['reloj-con-cargador.jpg'], escalas:[[10,50,101900],[51,100,93100],[101,null,90100]] },
  { id:'linterna-con-set', cat:'tecnologia', nombre:'Linterna con Set de Herramientas', ref:'T742', sinMarco:true,
    desc:'Linterna con set de herramientas. Batería de litio recargable. Linterna desmontable con base imantada.',
    fotos:['linterna-con-set.jpg'], escalas:[[10,50,64400],[51,100,54700],[101,null,51900]] },
  { id:'puerto-usb-einstein', cat:'tecnologia', nombre:'Puerto USB Einstein', ref:'TE-99', sinMarco:true,
    desc:'Puerto USB de 4 salidas. Medidas: 1.5 cm x 5 cm de diámetro.',
    fotos:['puerto-usb-einstein.jpg'], escalas:[[10,50,28990],[51,100,19800],[101,null,17500]] },
  { id:'soporte-para-celular', cat:'tecnologia', nombre:'Soporte para Celular', ref:'T629', sinMarco:true,
    desc:'Soporte de escritorio para celular con orificio que permite el paso del cable para facilitar la carga. Presentación en caja de regalo kraft.',
    fotos:['soporte-para-celular.jpg'], escalas:[[10,50,16300],[51,100,8600],[101,null,6700]] },
  { id:'power-banks', cat:'tecnologia', nombre:'Power Banks', ref:'Consultar', sinMarco:true,
    desc:'Nunca te quedes sin energía. Power banks personalizados que acompañan a tus clientes a todas partes.',
    fotos:['power-banks.jpg'], escalas:[], cotizacion:true },
  { id:'memorias-usb', cat:'tecnologia', nombre:'Memorias USB', ref:'Consultar', sinMarco:true,
    desc:'Conecta tu marca. USBs prácticos, funcionales y 100% personalizables.',
    fotos:['memorias-usb.jpg'], escalas:[], cotizacion:true },

  /* ---------- Reconocimientos ---------- */
  { id:'pin-con-tarjeta', cat:'reconocimientos', nombre:'Pin con Tarjeta', ref:'Consultar', sinMarco:true,
    desc:'Pin personalizado troquelado y pintado, presentado con tarjeta. Ideal para llevar tu marca a todas partes con estilo y personalidad.',
    fotos:['pin-con-tarjeta.jpg'], escalas:[], cotizacion:true },
  { id:'pin-pintado', cat:'reconocimientos', nombre:'Pin Pintado', ref:'Consultar', sinMarco:true,
    desc:'Pin en troquel pintado. Ideal para llevar tu marca a todas partes con estilo y personalidad.',
    fotos:['pin-pintado.jpg'], escalas:[], cotizacion:true },
  { id:'pin-litorrecina', cat:'reconocimientos', nombre:'Pin en Litorrecina', ref:'Consultar', sinMarco:true,
    desc:'Pin personalizado en litorrecina. Ideal para llevar tu marca a todas partes con estilo y personalidad.',
    fotos:['pin-litorrecina.jpg'], escalas:[], cotizacion:true },
  { id:'placa-reconocimiento', cat:'reconocimientos', nombre:'Placa de Reconocimiento', ref:'Consultar', sinMarco:true,
    desc:'Placa personalizada, ideal para reconocer el esfuerzo de tus colaboradores y de quienes dejan huella. Un detalle significativo que celebra logros y compromiso.',
    fotos:['placa-reconocimiento.jpg'], escalas:[], cotizacion:true },
  { id:'trofeo-base-pino', cat:'reconocimientos', nombre:'Trofeo con Base de Pino', ref:'Consultar', sinMarco:true,
    desc:'Elegante trofeo con cuerpo en acrílico cristal de 8 mm, grabado láser personalizado con texto y logotipo. Incluye base en madera de pino y placa frontal en acrílico negro grabado.',
    fotos:['trofeo-base-pino.jpg'], escalas:[], cotizacion:true },
  { id:'trofeos-zeus', cat:'reconocimientos', nombre:'Trofeos Zeus', ref:'Consultar', sinMarco:true,
    desc:'Trofeo en acrílico cristal de 8 mm de grosor con base del mismo material. Recubierto con acrílico espejo de 2 mm y grabado láser personalizado con textos y logotipos a color.',
    fotos:['trofeos-zeus.jpg'], escalas:[], cotizacion:true },
  { id:'trofeo-base-negra', cat:'reconocimientos', nombre:'Trofeo Base Negra', ref:'Consultar', sinMarco:true,
    desc:'Trofeo con cuerpo en acrílico cristal de 8 mm, grabado láser con textos y logotipos totalmente personalizados. Base en madera con acabado negro y placa frontal en acrílico.',
    fotos:['trofeo-base-negra.jpg'], escalas:[], cotizacion:true },
  { id:'trofeo-con-estrella', cat:'reconocimientos', nombre:'Trofeo con Estrella', ref:'Consultar', sinMarco:true,
    desc:'Diseño elegante y moderno, ideal para reconocer logros destacados. El cuerpo en vidrio cristal aporta distinción y la estrella metálica simboliza excelencia y superación.',
    fotos:['trofeo-con-estrella.jpg'], escalas:[], cotizacion:true },
  { id:'medallas-bano-oro', cat:'reconocimientos', nombre:'Medallas en Baño de Oro', ref:'Consultar', sinMarco:true,
    desc:'Medallas elaboradas en metal con acabado en baño de oro, ideales para premiaciones y reconocimientos especiales.',
    fotos:['medallas-bano-oro.jpg'], escalas:[], cotizacion:true },
  { id:'cintas-carnet', cat:'reconocimientos', nombre:'Cintas para Carnet', ref:'Consultar', sinMarco:true,
    desc:'Cintas para colgar carnet de cuello, personalizadas con tu logo y colores corporativos. Incluyen gancho metálico y opción de broche de seguridad.',
    fotos:['cintas-carnet.jpg'], escalas:[], cotizacion:true },

  /* ---------- Textil y Confección ---------- */
  { id:'camiseta-tshirt', cat:'textil', nombre:'Camiseta T-Shirt', ref:'Texcol', sinMarco:true,
    desc:'Camiseta tipo T-Shirt, cómoda y versátil, ideal para uso diario o eventos promocionales. Fabricada en materiales suaves y resistentes, perfecta para personalizar con tu marca.',
    fotos:['camiseta-tshirt.jpg'], escalas:[], cotizacion:true },
  { id:'camiseta-hombre', cat:'textil', nombre:'Camiseta Hombre', ref:'5000', sinMarco:true,
    desc:'Camiseta tipo T-Shirt disponible en varias tallas y colores, perfecta para cualquier ocasión y estilo.',
    fotos:['camiseta-hombre.jpg'], escalas:[], cotizacion:true },
  { id:'camiseta-mujer', cat:'textil', nombre:'Camiseta Mujer', ref:'5000L', sinMarco:true,
    desc:'Camiseta tipo T-Shirt disponible en varias tallas y colores, perfecta para cualquier ocasión y estilo.',
    fotos:['camiseta-mujer.jpg'], escalas:[], cotizacion:true },
  { id:'camisas-oxford', cat:'textil', nombre:'Camisas en Oxford', ref:'Consultar',
    desc:'Confeccionadas en tela Oxford de alta calidad, perfectas para uso corporativo, eventos empresariales o uniformes. Disponibles en varios colores y tallas, personalizables con bordado o estampado.',
    fotos:['camisas-oxford.jpg'], escalas:[], cotizacion:true },
  { id:'camiseta-polo', cat:'textil', nombre:'Camiseta tipo Polo', ref:'Consultar',
    desc:'Versátiles, cómodas y con estilo. Ideales para uniformes corporativos, eventos o promociones. Fabricadas en materiales de alta calidad tipo piqué o algodón, con opción de bordado o estampado.',
    fotos:['camiseta-polo.jpg'], escalas:[], cotizacion:true },
  { id:'buso-capota-dp', cat:'textil', nombre:'Buso con Capota DP', ref:'DP',
    desc:'Comodidad, abrigo y estilo en un solo producto. Ideal para uniformes, eventos o promociones. Disponible en varios colores y tallas, personalizable con bordado o estampado.',
    fotos:['buso-capota-dp.jpg','buso-capota-dp-2.jpg'], escalas:[], cotizacion:true },
  { id:'buso-manga-larga', cat:'textil', nombre:'Buso Manga Larga', ref:'Gildan',
    desc:'Comodidad, abrigo y estilo en un solo producto. Ideal para uniformes, eventos o promociones. Disponible en varios colores y tallas, personalizable con bordado o estampado.',
    fotos:['buso-manga-larga.jpg','buso-manga-larga-2.jpg'], escalas:[], cotizacion:true },
  { id:'buso-con-capota-gildan', cat:'textil', nombre:'Buso con Capota', ref:'Gildan',
    desc:'Comodidad, abrigo y estilo en un solo producto. Ideal para uniformes, eventos o promociones. Disponible en varios colores y tallas.',
    fotos:['buso-con-capota-gildan.jpg'], escalas:[], cotizacion:true },
  { id:'buso-cuello-cadete', cat:'textil', nombre:'Buso Cuello Cadete', ref:'Gildan',
    desc:'Comodidad, abrigo y estilo en un solo producto. Ideal para uniformes, eventos o promociones. Disponible en varios colores y tallas.',
    fotos:['buso-cuello-cadete.jpg'], escalas:[], cotizacion:true },
  { id:'chaqueta-urban-wear', cat:'textil', nombre:'Chaqueta Urban Wear', ref:'VA-666',
    desc:'Chaqueta rompevientos en poliéster de alta calidad con bolsa individual para cargar. Unisex, impermeable. Tallas S, M, L, XL. Marca por bordado.',
    fotos:['chaqueta-urban-wear.jpg'], escalas:[], cotizacion:true },

  /* ---------- Publicidad y POP ---------- */
  { id:'pendon-arana', cat:'publicidad', nombre:'Pendón tipo Araña', ref:'Consultar',
    desc:'Ideal para exhibiciones, eventos, puntos de venta y oficinas. Estructura liviana y fácil de armar, impresión en alta calidad sobre lona o tela. Incluye bolsa para transporte.',
    fotos:['pendon-arana.jpg'], escalas:[], cotizacion:true },
  { id:'pendon-roll-up', cat:'publicidad', nombre:'Pendón tipo Roll Up', ref:'Consultar',
    desc:'Ideal para exhibiciones, eventos, puntos de venta y oficinas. Estructura liviana y fácil de armar, impresión en alta calidad sobre lona o tela. Medidas estándar o personalizadas.',
    fotos:['pendon-roll-up.jpg'], escalas:[], cotizacion:true },
  { id:'acrilico', cat:'publicidad', nombre:'Acrílico', ref:'Consultar',
    desc:'Diseños modernos, resistentes y elegantes. Perfectos para trofeos, placas conmemorativas, señalización interna, porta nombres y más.',
    fotos:['acrilico.jpg'], escalas:[], cotizacion:true },
  { id:'calendario', cat:'publicidad', nombre:'Calendario', ref:'Consultar',
    desc:'Calendarios personalizados para tu empresa. Organiza, promociona y permanece presente todo el año.',
    fotos:['calendario.jpg'], escalas:[], cotizacion:true },
  { id:'aguas', cat:'publicidad', nombre:'Aguas Personalizadas', ref:'Consultar',
    desc:'Botellas con tu logo o mensaje, ideales para eventos, ferias, campañas o kits promocionales. Disponibles en diferentes tamaños y diseños.',
    fotos:['aguas.jpg'], escalas:[], cotizacion:true },
  { id:'dulces-chocolates', cat:'publicidad', nombre:'Dulces y Chocolates', ref:'Consultar',
    desc:'Chocolates, caramelos y confites con tu logo o diseño especial. Perfectos para eventos, campañas y regalos corporativos.',
    fotos:['dulces-chocolates.jpg'], escalas:[], cotizacion:true },

  /* ---------- Varios ---------- */
  { id:'ventilador-hook', cat:'varios', nombre:'Ventilador Hook', ref:'VA-1048', sinMarco:true,
    desc:'Ventilador en plástico con gancho carabinero. Pilas 3xAAA (no incluidas). Empaque caja individual.',
    fotos:['ventilador-hook.jpg'], escalas:[[10,50,33100],[51,100,23900],[101,null,21500]] },
  { id:'gafas-kilpan-eco', cat:'varios', nombre:'Gafas Kilpan Eco', ref:'VA-918', sinMarco:true,
    desc:'Gafas con marco plástico en PP con fibra de bambú, lentes con protección UV400. Medidas abierta: 15 cm x 14.8 cm.',
    fotos:['gafas-kilpan-eco.jpg'], escalas:[[10,50,21500],[51,100,12500],[101,null,10300]] },
  { id:'bola-antiestres-neon', cat:'varios', nombre:'Bola Antiestrés Neón', ref:'VA-89-2',
    desc:'Poliuretano. Sin bolsa individual. Medidas: 6.3 cm de diámetro.',
    fotos:['bola-antiestres-neon.jpg'], escalas:[[10,50,18400],[51,100,8700],[101,null,6500]] },
];

/* Valores de envío informativos (pág. 24 del catálogo) */
const ENVIOS = [
  { zona:'Entregas en Bogotá', valor:16500 },
  { zona:'Entregas en Sabana (Cajicá, Mosquera, Cota)', valor:23000 },
  { zona:'Ciudades principales (Medellín, Barranquilla)', valor:45000 }
];
